#!/usr/bin/env python3
"""
Batch download videos from a report generated by analyze.py.

Usage:
    python3 scripts/batch_download.py --report reports/foo.json --select 1,2,3
    python3 scripts/batch_download.py --report reports/foo.json --top 5
    python3 scripts/batch_download.py --report reports/foo.json --all

The report JSON is produced by analyze.py and contains a list of creatives
with their Ads Transparency URLs.
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import datetime, timedelta

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPTS_DIR)
DOWNLOADS_DIR = os.path.join(ROOT_DIR, "downloads")
CSV_DIR = os.path.join(ROOT_DIR, "csv")

# Import from sibling module
sys.path.insert(0, SCRIPTS_DIR)
from download import extract_from_ads_transparency, download_video


def resolve_output_dir(report, output_dir_override=None):
    """Build output dir as downloads/YYYY-MM-DD_REGION from report metadata."""
    if output_dir_override:
        return output_dir_override

    params = report.get("analysis", {}).get("search_params", {})
    region = params.get("region", "XX").upper()
    date_preset = params.get("date", "Yesterday")
    generated_at = report.get("generated_at", "")

    try:
        report_date = datetime.fromisoformat(generated_at).date()
    except Exception:
        report_date = datetime.now().date()

    date_map = {
        "Yesterday": report_date - timedelta(days=1),
        "Last 7 days": report_date - timedelta(days=7),
        "Last 30 days": report_date - timedelta(days=30),
    }
    target_date = date_map.get(date_preset, report_date)
    folder_name = f"{target_date.isoformat()}_{region}"

    return os.path.join(DOWNLOADS_DIR, folder_name)


def load_report(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def select_creatives(creatives, select_str=None, top_n=None, select_all=False):
    """Return a filtered list of creatives based on user selection."""
    if select_all:
        return creatives

    if top_n:
        return creatives[:top_n]

    if select_str:
        indices = []
        for part in select_str.split(","):
            part = part.strip()
            if "-" in part:
                start, end = part.split("-", 1)
                indices.extend(range(int(start), int(end) + 1))
            else:
                indices.append(int(part))
        return [creatives[i - 1] for i in indices if 0 < i <= len(creatives)]

    return []


def main():
    parser = argparse.ArgumentParser(
        description="Download em lote a partir de relatório do analyze.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Exemplos:
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --select 1,2,3
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --select 1-5
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --top 10
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --all
        """,
    )

    parser.add_argument("--report", required=True, help="Caminho para o relatório JSON gerado pelo analyze.py")
    parser.add_argument("--select", help="Índices dos criativos para baixar (ex: 1,2,3 ou 1-5)")
    parser.add_argument("--top", type=int, help="Baixar os N primeiros criativos")
    parser.add_argument("--all", action="store_true", dest="select_all", help="Baixar todos os criativos")
    parser.add_argument("--output-dir", default=None, help="Pasta de destino (default: downloads/YYYY-MM-DD_REGION/)")
    parser.add_argument("--csv-only", action="store_true", help="Apenas gerar CSV com URLs (sem download)")

    args = parser.parse_args()

    if not args.select and not args.top and not args.select_all:
        parser.print_help()
        print("\nERRO: Forneça --select, --top ou --all")
        sys.exit(1)

    report = load_report(args.report)
    creatives = report.get("creatives", [])

    if not creatives:
        print("  Nenhum criativo encontrado no relatório.")
        sys.exit(1)

    selected = select_creatives(creatives, args.select, args.top, args.select_all)

    if not selected:
        print("  Nenhum criativo selecionado.")
        sys.exit(1)

    output_dir = resolve_output_dir(report, args.output_dir)

    mode = "CSV only" if args.csv_only else "Download"
    print(f"\n  Batch {mode} — {len(selected)} criativo(s) selecionado(s)")
    print(f"  Destino: {output_dir}\n")

    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(CSV_DIR, exist_ok=True)

    params = report.get("analysis", {}).get("search_params", {})
    region = params.get("region", "")
    date_filter = params.get("date", "")

    # --- Phase 1: extract YouTube video info from each creative ---
    print("  Fase 1/2 — Extraindo URLs de vídeo...\n")
    enriched = []

    for i, creative in enumerate(selected, 1):
        url = creative.get("url", "")
        cid = creative.get("creative_id", "?")
        name = creative.get("advertiser_name", "?")

        print(f"  [{i}/{len(selected)}] CR:{cid[:20]}... — {name}")

        if not url or "adstransparency.google.com" not in url:
            print(f"    SKIP: URL inválida")
            enriched.append({**creative, "_videos": []})
            continue

        try:
            videos = extract_from_ads_transparency(url)
            enriched.append({**creative, "_videos": videos or []})
            if not videos:
                print(f"    Nenhum vídeo YouTube encontrado")
            else:
                for v in videos:
                    yt_url = f"https://www.youtube.com/shorts/{v['id']}" if v.get("is_short") else f"https://www.youtube.com/watch?v={v['id']}"
                    print(f"    -> {yt_url}")
        except Exception as e:
            print(f"    ERRO: {e}")
            enriched.append({**creative, "_videos": []})

        print()

    # --- Save CSV with all enriched data ---
    csv_name = os.path.basename(output_dir) + ".csv"
    urls_path = os.path.join(CSV_DIR, csv_name)
    csv_row_idx = 0
    with open(urls_path, "w", encoding="utf-8") as f:
        f.write("index,advertiser_name,ads_transparency_url,video_url,youtube_channel,region,date_filter\n")
        for c in enriched:
            videos = c.get("_videos", [])
            if not videos:
                csv_row_idx += 1
                row = [
                    str(csv_row_idx),
                    _csv_escape(c.get("advertiser_name", "")),
                    c.get("url", ""),
                    "",
                    "",
                    region,
                    date_filter,
                ]
                f.write(",".join(row) + "\n")
            else:
                for v in videos:
                    csv_row_idx += 1
                    yt_url = f"https://www.youtube.com/shorts/{v['id']}" if v.get("is_short") else f"https://www.youtube.com/watch?v={v['id']}"
                    row = [
                        str(csv_row_idx),
                        _csv_escape(c.get("advertiser_name", "")),
                        c.get("url", ""),
                        yt_url,
                        _csv_escape(v.get("channel", "") or ""),
                        region,
                        date_filter,
                    ]
                    f.write(",".join(row) + "\n")
    print(f"  CSV salvo em: {urls_path}  ({csv_row_idx} linhas)\n")

    if args.csv_only:
        print(f"  {'=' * 50}")
        print(f"  Modo --csv-only: download pulado")
        print(f"  CSV em: {urls_path}")
        print(f"  {'=' * 50}\n")
        return

    # --- Phase 2: download videos ---
    print("  Fase 2/2 — Baixando vídeos...\n")
    success = 0
    failed = 0
    start_time = time.time()

    for i, creative in enumerate(enriched, 1):
        videos = creative.get("_videos", [])

        if not videos:
            failed += 1
            continue

        for v in videos:
            try:
                result = download_video(v, output_dir)
                if result:
                    success += 1
                else:
                    failed += 1
            except Exception as e:
                print(f"    ERRO download: {e}")
                failed += 1

    elapsed = time.time() - start_time

    print(f"  {'=' * 50}")
    print(f"  Concluído em {elapsed:.0f}s")
    print(f"  Sucesso: {success}  |  Falha: {failed}")
    print(f"  Arquivos em: {output_dir}")
    print(f"  CSV em:      {urls_path}")
    print(f"  {'=' * 50}\n")


def _csv_escape(value):
    """Wrap value in quotes if it contains commas or quotes."""
    s = str(value)
    if "," in s or '"' in s or "\n" in s:
        return '"' + s.replace('"', '""') + '"'
    return s


if __name__ == "__main__":
    if not os.environ.get("PLAYWRIGHT_BROWSERS_PATH"):
        default_path = os.path.expanduser("~/Library/Caches/ms-playwright")
        if os.path.isdir(default_path):
            os.environ["PLAYWRIGHT_BROWSERS_PATH"] = default_path

    main()
