#!/usr/bin/env python3
"""
Batch download videos from a report generated by analyze.py.

Usage:
    python3 scripts/batch_download.py --report reports/foo.json --select 1,2,3
    python3 scripts/batch_download.py --report reports/foo.json --top 5
    python3 scripts/batch_download.py --report reports/foo.json --all

The report JSON is produced by analyze.py and contains a list of creatives
with their Ads Transparency URLs.
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import datetime, timedelta

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
DOWNLOADS_DIR = os.path.join(os.path.dirname(SCRIPTS_DIR), "downloads")

# Import from sibling module
sys.path.insert(0, SCRIPTS_DIR)
from download import extract_from_ads_transparency, download_video


def resolve_output_dir(report, output_dir_override=None):
    """Build output dir as downloads/YYYY-MM-DD_REGION from report metadata."""
    if output_dir_override:
        return output_dir_override

    params = report.get("analysis", {}).get("search_params", {})
    region = params.get("region", "XX").upper()
    date_preset = params.get("date", "Yesterday")
    generated_at = report.get("generated_at", "")

    try:
        report_date = datetime.fromisoformat(generated_at).date()
    except Exception:
        report_date = datetime.now().date()

    date_map = {
        "Yesterday": report_date - timedelta(days=1),
        "Last 7 days": report_date - timedelta(days=7),
        "Last 30 days": report_date - timedelta(days=30),
    }
    target_date = date_map.get(date_preset, report_date)
    folder_name = f"{target_date.isoformat()}_{region}"

    return os.path.join(DOWNLOADS_DIR, folder_name)


def load_report(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def select_creatives(creatives, select_str=None, top_n=None, select_all=False):
    """Return a filtered list of creatives based on user selection."""
    if select_all:
        return creatives

    if top_n:
        return creatives[:top_n]

    if select_str:
        indices = []
        for part in select_str.split(","):
            part = part.strip()
            if "-" in part:
                start, end = part.split("-", 1)
                indices.extend(range(int(start), int(end) + 1))
            else:
                indices.append(int(part))
        return [creatives[i - 1] for i in indices if 0 < i <= len(creatives)]

    return []


def main():
    parser = argparse.ArgumentParser(
        description="Download em lote a partir de relatório do analyze.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Exemplos:
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --select 1,2,3
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --select 1-5
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --top 10
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --all
        """,
    )

    parser.add_argument("--report", required=True, help="Caminho para o relatório JSON gerado pelo analyze.py")
    parser.add_argument("--select", help="Índices dos criativos para baixar (ex: 1,2,3 ou 1-5)")
    parser.add_argument("--top", type=int, help="Baixar os N primeiros criativos")
    parser.add_argument("--all", action="store_true", dest="select_all", help="Baixar todos os criativos")
    parser.add_argument("--output-dir", default=None, help="Pasta de destino (default: downloads/YYYY-MM-DD_REGION/)")

    args = parser.parse_args()

    if not args.select and not args.top and not args.select_all:
        parser.print_help()
        print("\nERRO: Forneça --select, --top ou --all")
        sys.exit(1)

    report = load_report(args.report)
    creatives = report.get("creatives", [])

    if not creatives:
        print("  Nenhum criativo encontrado no relatório.")
        sys.exit(1)

    selected = select_creatives(creatives, args.select, args.top, args.select_all)

    if not selected:
        print("  Nenhum criativo selecionado.")
        sys.exit(1)

    output_dir = resolve_output_dir(report, args.output_dir)

    print(f"\n  Batch Download — {len(selected)} criativo(s) selecionado(s)")
    print(f"  Destino: {output_dir}\n")

    os.makedirs(output_dir, exist_ok=True)

    # Save original URLs before downloading
    urls_path = os.path.join(output_dir, "urls.csv")
    with open(urls_path, "w", encoding="utf-8") as f:
        f.write("index,creative_id,advertiser_id,advertiser_name,format,verified,ads_transparency_url\n")
        for i, c in enumerate(selected, 1):
            row = [
                str(i),
                c.get("creative_id", ""),
                c.get("advertiser_id", ""),
                f'"{c.get("advertiser_name", "")}"',
                c.get("format", ""),
                str(c.get("verified", False)),
                c.get("url", ""),
            ]
            f.write(",".join(row) + "\n")
    print(f"  URLs originais salvas em: {urls_path}\n")

    success = 0
    failed = 0
    start_time = time.time()

    for i, creative in enumerate(selected, 1):
        url = creative.get("url", "")
        cid = creative.get("creative_id", "?")
        name = creative.get("advertiser_name", "?")

        print(f"  [{i}/{len(selected)}] CR:{cid[:20]}... — {name}")

        if not url or "adstransparency.google.com" not in url:
            print(f"    SKIP: URL inválida")
            failed += 1
            continue

        try:
            videos = extract_from_ads_transparency(url)

            if not videos:
                print(f"    SKIP: Nenhum vídeo YouTube encontrado")
                failed += 1
                continue

            for v in videos:
                result = download_video(v, output_dir)
                if result:
                    success += 1
                else:
                    failed += 1
        except Exception as e:
            print(f"    ERRO: {e}")
            failed += 1

        print()

    elapsed = time.time() - start_time

    print(f"  {'=' * 50}")
    print(f"  Concluído em {elapsed:.0f}s")
    print(f"  Sucesso: {success}  |  Falha: {failed}")
    print(f"  Arquivos em: {output_dir}")
    print(f"  {'=' * 50}\n")


if __name__ == "__main__":
    if not os.environ.get("PLAYWRIGHT_BROWSERS_PATH"):
        default_path = os.path.expanduser("~/Library/Caches/ms-playwright")
        if os.path.isdir(default_path):
            os.environ["PLAYWRIGHT_BROWSERS_PATH"] = default_path

    main()
