#!/usr/bin/env python3
"""
Batch download videos from a report generated by analyze.py.

Usage:
    python3 scripts/batch_download.py --report reports/foo.json --select 1,2,3
    python3 scripts/batch_download.py --report reports/foo.json --top 5
    python3 scripts/batch_download.py --report reports/foo.json --all

The report JSON is produced by analyze.py and contains a list of creatives
with their Ads Transparency URLs.
"""

import argparse
import json
import os
import sys
import time

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
DOWNLOADS_DIR = os.path.join(os.path.dirname(SCRIPTS_DIR), "downloads")

# Import from sibling module
sys.path.insert(0, SCRIPTS_DIR)
from download import extract_from_ads_transparency, download_video


def load_report(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def select_creatives(creatives, select_str=None, top_n=None, select_all=False):
    """Return a filtered list of creatives based on user selection."""
    if select_all:
        return creatives

    if top_n:
        return creatives[:top_n]

    if select_str:
        indices = []
        for part in select_str.split(","):
            part = part.strip()
            if "-" in part:
                start, end = part.split("-", 1)
                indices.extend(range(int(start), int(end) + 1))
            else:
                indices.append(int(part))
        return [creatives[i - 1] for i in indices if 0 < i <= len(creatives)]

    return []


def main():
    parser = argparse.ArgumentParser(
        description="Download em lote a partir de relatório do analyze.py",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Exemplos:
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --select 1,2,3
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --select 1-5
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --top 10
  python3 scripts/batch_download.py --report reports/robloxos_US_20260423.json --all
        """,
    )

    parser.add_argument("--report", required=True, help="Caminho para o relatório JSON gerado pelo analyze.py")
    parser.add_argument("--select", help="Índices dos criativos para baixar (ex: 1,2,3 ou 1-5)")
    parser.add_argument("--top", type=int, help="Baixar os N primeiros criativos")
    parser.add_argument("--all", action="store_true", dest="select_all", help="Baixar todos os criativos")
    parser.add_argument("--output-dir", default=DOWNLOADS_DIR, help=f"Pasta de destino (default: downloads/)")

    args = parser.parse_args()

    if not args.select and not args.top and not args.select_all:
        parser.print_help()
        print("\nERRO: Forneça --select, --top ou --all")
        sys.exit(1)

    report = load_report(args.report)
    creatives = report.get("creatives", [])

    if not creatives:
        print("  Nenhum criativo encontrado no relatório.")
        sys.exit(1)

    selected = select_creatives(creatives, args.select, args.top, args.select_all)

    if not selected:
        print("  Nenhum criativo selecionado.")
        sys.exit(1)

    print(f"\n  Batch Download — {len(selected)} criativo(s) selecionado(s)")
    print(f"  Destino: {args.output_dir}\n")

    os.makedirs(args.output_dir, exist_ok=True)

    success = 0
    failed = 0
    start_time = time.time()

    for i, creative in enumerate(selected, 1):
        url = creative.get("url", "")
        cid = creative.get("creative_id", "?")
        name = creative.get("advertiser_name", "?")

        print(f"  [{i}/{len(selected)}] CR:{cid[:20]}... — {name}")

        if not url or "adstransparency.google.com" not in url:
            print(f"    SKIP: URL inválida")
            failed += 1
            continue

        try:
            videos = extract_from_ads_transparency(url)

            if not videos:
                print(f"    SKIP: Nenhum vídeo YouTube encontrado")
                failed += 1
                continue

            for v in videos:
                result = download_video(v, args.output_dir)
                if result:
                    success += 1
                else:
                    failed += 1
        except Exception as e:
            print(f"    ERRO: {e}")
            failed += 1

        print()

    elapsed = time.time() - start_time

    print(f"  {'=' * 50}")
    print(f"  Concluído em {elapsed:.0f}s")
    print(f"  Sucesso: {success}  |  Falha: {failed}")
    print(f"  Arquivos em: {args.output_dir}")
    print(f"  {'=' * 50}\n")


if __name__ == "__main__":
    if not os.environ.get("PLAYWRIGHT_BROWSERS_PATH"):
        default_path = os.path.expanduser("~/Library/Caches/ms-playwright")
        if os.path.isdir(default_path):
            os.environ["PLAYWRIGHT_BROWSERS_PATH"] = default_path

    main()
