#!/usr/bin/env python3
"""
Download Meta Ads Library video creatives — lightweight, no Playwright needed.

Designed to work with the MCP workflow:
  1. The Cursor agent uses MCP DevTools to navigate + extract video data
  2. The agent saves a report JSON (or passes URLs directly)
  3. This script downloads the MP4 files from Facebook CDN URLs

No browser dependency — just requests + optional yt-dlp fallback.

Usage:
    # From a report JSON generated by the agent via MCP
    python3 scripts/meta_download.py --report reports/meta_nike_US_20260425.json --all
    python3 scripts/meta_download.py --report reports/meta_nike_US_20260425.json --top 5
    python3 scripts/meta_download.py --report reports/meta_nike_US_20260425.json --select 1,3,5

    # Direct URL download (one or more CDN URLs)
    python3 scripts/meta_download.py --urls "https://video.xx.fbcdn.net/..." "https://video.xx.fbcdn.net/..."

    # Direct download by Library ID (uses yt-dlp, no MCP needed)
    python3 scripts/meta_download.py --library-id 1234567890
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime
from urllib.request import Request, urlopen

SCRIPTS_DIR   = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR      = os.path.dirname(SCRIPTS_DIR)
DOWNLOADS_DIR = os.path.join(ROOT_DIR, "downloads")
CSV_DIR       = os.path.join(ROOT_DIR, "csv")

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_report(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def select_creatives(creatives, select_str=None, top_n=None, select_all=False):
    if select_all:
        return list(enumerate(creatives, 1))
    if top_n:
        return list(enumerate(creatives[:top_n], 1))
    if select_str:
        indices = []
        for part in select_str.split(","):
            part = part.strip()
            if "-" in part:
                start, end = part.split("-", 1)
                indices.extend(range(int(start), int(end) + 1))
            else:
                indices.append(int(part))
        return [(i, creatives[i - 1]) for i in indices if 0 < i <= len(creatives)]
    return []


def resolve_output_dir(report, override=None):
    if override:
        return override
    params  = report.get("analysis", {}).get("search_params", {})
    country = params.get("country", "XX").upper()
    ts      = report.get("generated_at", datetime.now().isoformat())
    try:
        date_str = datetime.fromisoformat(ts).strftime("%Y-%m-%d")
    except Exception:
        date_str = datetime.now().strftime("%Y-%m-%d")
    return os.path.join(DOWNLOADS_DIR, f"{date_str}_{country}_meta")


def sanitize(name, max_len=40):
    s = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", str(name or "unknown"))
    s = re.sub(r"\s+", "-", s).strip("-_")
    return s[:max_len] if s else "unknown"


def build_filename(index, creative):
    lib_id   = creative.get("library_id") or f"idx{index}"
    adv      = sanitize(creative.get("advertiser_name") or "")
    date_str = datetime.now().strftime("%m%d")
    return f"meta_{lib_id}_{adv}_{date_str}_{index:03d}.mp4"


def csv_escape(value):
    s = str(value)
    if "," in s or '"' in s or "\n" in s:
        return '"' + s.replace('"', '""') + '"'
    return s


# ---------------------------------------------------------------------------
# Download functions
# ---------------------------------------------------------------------------

def download_cdn_url(url, dest_path):
    """Download an MP4 directly from Facebook CDN. No browser needed."""
    headers = {
        "User-Agent":      UA,
        "Referer":         "https://www.facebook.com/",
        "Accept":          "video/webm,video/mp4,video/*;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
    }

    req = Request(url, headers=headers)
    with urlopen(req, timeout=90) as resp, open(dest_path, "wb") as f:
        total      = int(resp.headers.get("Content-Length", 0))
        downloaded  = 0
        chunk_size  = 256 * 1024

        while True:
            chunk = resp.read(chunk_size)
            if not chunk:
                break
            f.write(chunk)
            downloaded += len(chunk)
            if total:
                pct = downloaded / total * 100
                mb  = downloaded // (1024 * 1024)
                tot = total // (1024 * 1024)
                print(f"\r    {pct:5.1f}% ({mb} MB / {tot} MB)", end="", flush=True)

    print()
    size = os.path.getsize(dest_path)
    if size < 10_000:
        os.remove(dest_path)
        return False
    return True


def download_with_ytdlp(ad_url, dest_path):
    """Fallback: use yt-dlp to download from a Facebook ad page URL."""
    output_tpl = dest_path.replace(".mp4", ".%(ext)s")
    cmd = [
        "yt-dlp",
        "--cookies-from-browser", "chrome",
        "--format", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
        "--output", output_tpl,
        "--no-playlist", "--quiet", "--progress",
        ad_url,
    ]
    result = subprocess.run(cmd, capture_output=False)
    if result.returncode == 0:
        for ext in (".mp4", ".mkv", ".webm"):
            candidate = dest_path.replace(".mp4", ext)
            if os.path.exists(candidate) and os.path.getsize(candidate) > 10_000:
                if candidate != dest_path:
                    os.rename(candidate, dest_path)
                return True
    return False


def download_creative(index, creative, output_dir):
    """Download a single creative. Tries CDN URL first, then yt-dlp fallback."""
    filename  = build_filename(index, creative)
    dest_path = os.path.join(output_dir, filename)

    if os.path.exists(dest_path) and os.path.getsize(dest_path) > 10_000:
        print(f"    SKIP (já existe): {filename}")
        return True, filename

    video_url = creative.get("video_url", "")
    ad_url    = creative.get("ad_url", "")
    lib_id    = creative.get("library_id") or f"idx{index}"

    # Try direct CDN download
    if video_url and video_url.startswith("http") and not video_url.startswith("blob:"):
        print(f"    CDN: {video_url[:80]}...")
        try:
            ok = download_cdn_url(video_url, dest_path)
            if ok:
                size_mb = os.path.getsize(dest_path) / (1024 * 1024)
                print(f"    OK  {size_mb:.1f} MB")
                return True, filename
            else:
                print(f"    CDN falhou (arquivo muito pequeno)")
        except Exception as e:
            print(f"    CDN falhou: {e}")

    # Fallback: yt-dlp with the ad page URL
    if ad_url:
        print(f"    Tentando yt-dlp: {ad_url}")
        ok = download_with_ytdlp(ad_url, dest_path)
        if ok:
            size_mb = os.path.getsize(dest_path) / (1024 * 1024)
            print(f"    OK via yt-dlp  {size_mb:.1f} MB")
            return True, filename

    print(f"    FALHOU: sem URL válida para download")
    return False, filename


# ---------------------------------------------------------------------------
# CSV export
# ---------------------------------------------------------------------------

def save_csv(enriched, output_dir, search_params):
    os.makedirs(CSV_DIR, exist_ok=True)
    csv_name = os.path.basename(output_dir) + ".csv"
    csv_path = os.path.join(CSV_DIR, csv_name)

    country     = search_params.get("country", "")
    query       = search_params.get("query", "")

    with open(csv_path, "w", encoding="utf-8") as f:
        f.write("index,library_id,advertiser_name,video_url,ad_url,country,query\n")
        for i, c in enumerate(enriched, 1):
            row = [
                str(i),
                c.get("library_id") or "",
                csv_escape(c.get("advertiser_name") or ""),
                c.get("video_url") or "",
                c.get("ad_url") or "",
                country,
                csv_escape(query),
            ]
            f.write(",".join(row) + "\n")

    print(f"  CSV salvo: {csv_path}  ({len(enriched)} linhas)")
    return csv_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Download de criativos Meta Ads Library (sem Playwright)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Exemplos:
  # A partir de relatório JSON (gerado pelo agente via MCP)
  python3 scripts/meta_download.py --report reports/meta_nike_US_*.json --all
  python3 scripts/meta_download.py --report reports/meta_nike_US_*.json --top 5
  python3 scripts/meta_download.py --report reports/meta_nike_US_*.json --select 1-10

  # URLs diretas da CDN
  python3 scripts/meta_download.py --urls "https://video.xx.fbcdn.net/v/..." --output-dir downloads/meta_test

  # Por Library ID (usa yt-dlp como fallback)
  python3 scripts/meta_download.py --library-id 1234567890
        """,
    )
    parser.add_argument("--report",     help="Relatório JSON do meta_analyze ou gerado pelo agente MCP")
    parser.add_argument("--select",     help="Índices (ex: 1,2,3 ou 1-5)")
    parser.add_argument("--top",        type=int, help="Baixar os N primeiros")
    parser.add_argument("--all",        action="store_true", dest="select_all", help="Baixar todos")
    parser.add_argument("--output-dir", help="Pasta de destino")
    parser.add_argument("--csv-only",   action="store_true", help="Apenas gerar CSV")
    # Direct modes
    parser.add_argument("--urls",       nargs="+", help="URLs CDN diretas para download")
    parser.add_argument("--library-id", help="Facebook Library ID (usa yt-dlp)")
    parser.add_argument("--advertiser", default="unknown", help="Nome do anunciante (para nomear arquivo)")

    args = parser.parse_args()

    # --- Direct URL mode ---
    if args.urls:
        output_dir = args.output_dir or os.path.join(
            DOWNLOADS_DIR, datetime.now().strftime("%Y-%m-%d") + "_meta"
        )
        os.makedirs(output_dir, exist_ok=True)
        print(f"\n  Meta Download — {len(args.urls)} URL(s)")
        print(f"  Destino: {output_dir}\n")

        ok_count = 0
        for i, url in enumerate(args.urls, 1):
            creative = {"video_url": url, "advertiser_name": args.advertiser, "library_id": f"url{i}"}
            ok, fname = download_creative(i, creative, output_dir)
            if ok:
                ok_count += 1
        print(f"\n  Concluído: {ok_count}/{len(args.urls)}")
        sys.exit(0)

    # --- Library ID mode ---
    if args.library_id:
        ad_url = f"https://www.facebook.com/ads/library/?id={args.library_id}"
        output_dir = args.output_dir or os.path.join(
            DOWNLOADS_DIR, datetime.now().strftime("%Y-%m-%d") + "_meta"
        )
        os.makedirs(output_dir, exist_ok=True)
        creative = {
            "library_id": args.library_id,
            "advertiser_name": args.advertiser,
            "ad_url": ad_url,
        }
        print(f"\n  Meta Download — Library ID {args.library_id}")
        print(f"  Destino: {output_dir}\n")
        ok, fname = download_creative(1, creative, output_dir)
        print(f"\n  {'OK' if ok else 'FALHOU'}: {fname}")
        sys.exit(0 if ok else 1)

    # --- Report mode ---
    if not args.report:
        parser.print_help()
        print("\nERRO: Forneça --report, --urls ou --library-id")
        sys.exit(1)

    if not args.select and not args.top and not args.select_all:
        parser.print_help()
        print("\nERRO: Forneça --select, --top ou --all")
        sys.exit(1)

    report    = load_report(args.report)
    creatives = report.get("creatives", [])
    if not creatives:
        print("  Nenhum criativo no relatório.")
        sys.exit(1)

    selected = select_creatives(creatives, args.select, args.top, args.select_all)
    if not selected:
        print("  Nenhum criativo selecionado.")
        sys.exit(1)

    output_dir = resolve_output_dir(report, args.output_dir)
    os.makedirs(output_dir, exist_ok=True)

    params  = report.get("analysis", {}).get("search_params", {})
    query   = params.get("query") or params.get("page_id") or "meta"
    country = params.get("country", "")

    print(f"\n  Meta Ads Download — {len(selected)} criativo(s)")
    print(f"  Busca:   {query} / {country}")
    print(f"  Destino: {output_dir}\n")

    # CSV
    all_creatives = [c for _, c in selected]
    csv_path = save_csv(all_creatives, output_dir, params)

    if args.csv_only:
        print(f"\n  Modo --csv-only: download pulado")
        print(f"  CSV em: {csv_path}\n")
        return

    # Download
    success = 0
    failed  = 0
    start   = time.time()

    for idx, creative in selected:
        adv = creative.get("advertiser_name") or "?"
        lid = creative.get("library_id") or "?"
        print(f"\n  [{idx}/{len(creatives)}] {lid} — {adv}")

        ok, fname = download_creative(idx, creative, output_dir)
        if ok:
            success += 1
        else:
            failed += 1

    elapsed = time.time() - start
    print(f"\n  {'=' * 50}")
    print(f"  Concluído em {elapsed:.0f}s")
    print(f"  Sucesso: {success}  |  Falha: {failed}")
    print(f"  Arquivos: {output_dir}")
    print(f"  CSV:      {csv_path}")
    print(f"  {'=' * 50}\n")


if __name__ == "__main__":
    main()
